### ISSUE TITLE
improve test coverage for orders.go file

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-api-go#40]
**Is your feature request related to a problem? Please describe.**
Extend the tests for the `orders` resource, this is the only file in which we don't have more than 90% coverage.

**Describe the solution you'd like**
Force errors and test that the client is handling those errors gracefully without breaking the existing tests.

You can follow [customers.go](https://github.com/VictorAvelar/mollie-api-go/blob/master/mollie/customers_test.go) test suite as an example.

**Additional context**
If you have any concern or question, please feel free to address it in the comments.

**Comment by dwikur21** [comment]
@VictorAvelar sorry I didn't read your edited comment https://github.com/VictorAvelar/mollie-api-go/pull/36#pullrequestreview-304244445
I will be taking this. I need to add NewAPIRequestErrors, JsonDecodingErrors and HTTPRequestErrors right?
Because in the current code, I just follow the docs where I just create a test if there are error responses

**Comment by VictorAvelar** [comment]
Yup, is for checking that when errors occur we can handle them properly 😄
